### ISSUE TITLE
Shorter module names.

### ISSUE THREAD

**Issue by Lemmih** [noinia/hgeometry#111]
Some module names are quite long (such as `Algorithms.Geometry.WellSeparatedPairDecomposition.WSPD`) and we're not being too consistent with the naming schemes. Sometimes we use an abbreviation (like `Algorithms.Geometry.SoS` and `Algorithms.Geometry.EuclideanMST`) and other times we write out the name in full. I suggest we use abbreviations when possible and also use more general groupings (eg. rename `PolygonTriangulation` to just `Triangulation`).

Specific changes I'm proposing:
 - Rename `PolygonTriangulation` to `Triangulation`.
 - Rename `WellSeparatedPairDecomposition` to `WSPD` (make it re-export `Algorithms.Geometry.WellSeparatedPairDecomposition.WSPD` and `Algorithms.Geometry.WellSeparatedPairDecomposition.Types`).
 - Rename `LineSegmentIntersection` to `Intersection`.
 - Rename `PolyLineSimplification` to `Simplification`.
 - Rename `DelaunayTriangulation` to `Delaunay`.
 - Rename `Algorithms.Geometry.EuclideanMST.EuclideanMST` to `Algorithms.Geometry.EuclideanMST`.

I'd also like to merge all of `Algorithm.Geometry.PolygonTriangulation.*` into `Algorithm.Geometry.Triangulation.Monotone`. Then `Algorithm.Geometry.Triangulation` should re-export a general triangulation function.

Deprecation schedule: I suggest we mark the old modules as deprecated and schedule them for removal in six months.

What do you think, @noinia?

**Comment by noinia** [comment]
Hmm, in general I like the descriptive names, moreover I don't there is much of a cost in having descriptive module names as you typically just import them only once in a module anyway. However, maybe we can shorten things like ''Algorithms.Geometry.WellSeparatedPairDecomposition.WSPD' for which there is only one "obvious" implementation just to 'Algorithms.Geometry.WellSepartedPairDecomposition', or even 'Algorithms.Geometry.WSPD'. Same for the EuclideanMST module. For the other ones I think shortening them makes the names less descriptive, for no good reason.

**Comment by Lemmih** [comment]
Okay, good, so we agree on these two changes:
 - `Algorithms.Geometry.EuclideanMST.EuclideanMST` to `Algorithms.Geometry.EuclideanMST`.
 - `Algorithms.Geometry.WellSeparatedPairDecomposition.WSPD` to `Algorithms.Geometry.WSPD`

And I assume you're fine with me adding `Algorithms.Geometry.ClosestPair`, `Algorithms.Geometry.ConvexHull`, `Algorithms.Geometry.DelaunayTriangulation`, `Algorithms.Geometry.Diameter`, and `Algorithms.Geometry.PolygonTriangulation`. When there are multiple choices, these modules will re-export the blessed algorithm.

I'll push forward with these changes. Still think you're underestimating the cognitive cost of long module names but this will become more apparent as HGeometry grows and we can take it up again later.

**Comment by noinia** [comment]
The above sounds good to me.

**Comment by Lemmih** [comment]
Fixed in #112.
