### ISSUE TITLE
Release 0.12.0.2

### ISSUE THREAD

**Issue by Lemmih** [noinia/hgeometry#133]
Hi @noinia. Could you upload hgeometry-0.12.0.2 to hackage from the `stable-0.12` branch? It moves a test-related executable to the `hgeometry-test` package which is required by stackage. Thanks.

**Comment by noinia** [comment]
Done. I will likely drop support for GHC-8.4 in the near future, and remove it from the CI, since I now had to set an upperbound on vector-builder.

**Comment by Lemmih** [comment]
Hm, the upper bound is causing trouble with stack. Would you mind if we only enabled it for ghc <= 8.4?
