### ISSUE TITLE
Haskell.nix: error: The Nixpkgs package set does not contain the package: m (system dependency).

### ISSUE THREAD

**Issue by o1lo01ol1o** [noinia/hgeometry#135]
Hi, started a project with this as a dependency using haskell.nix, but something in `hgeometry` is trying to pull in a dependency called "m" that my system is unable to find.  Do you have any idea what this might be?

**Comment by Lemmih** [comment]
libm, maybe? You might be better off asking in nix discord or nix IRC.

**Comment by o1lo01ol1o** [comment]
@Lemmih Do you know which `hgeometry` component depends on libm?  Should the corrresponding `cabal` file not contain something like the following?

```
if os(windows)
      extra-libraries:
        libm
    else
      if os(darwin)
        extra-libraries:
          libm
      else
        pkgconfig-depends:
          libm
```

**Comment by Lemmih** [comment]
All Haskell code compiled with GHC uses libm. This is not an hgeometry issue; It's a nix issue. I suggest you ask in the nix discord or IRC servers.

**Comment by o1lo01ol1o** [comment]
@Lemmih I was directed to here by the `haskell.nix` IRC channel when I was trying to determine if the above referenced error was a referring to something in  the `haskell.nix` infrastructure.

The error is an issue with `hgeometry` and `haskell.nix`; other dependencies compile.

**Comment by Lemmih** [comment]
Well, I can promise you it's not an hgeometry issue. But feel free to post the solution here when you find it.

**Comment by ramirez7** [comment]
@o1lo01ol1o I ran into this issue too and fixed it.

I just [added `m` to my package set with this overlay](https://input-output-hk.github.io/haskell.nix/tutorials/pkg-map/#nixpkgs-overlay):
```nix
self: super:

{
  m = self.stdenv.mkDerivation {
    name = "m";
    unpackPhase = "true";
    installPhase = "mkdir -p $out";
  };
}
```

[I made an issue with `haskell.nix` here.](https://input-output-hk.github.io/haskell.nix/tutorials/pkg-map/#nixpkgs-overlay)

**Comment by ramirez7** [comment]
@o1lo01ol1o When x-compiling to Windows (`mingwW64`), `remote-iserv` failed due to issues open files/creating directories with `libm`. I was able to get `hgeometry` x-compiling by tweaking my overlay to create `lib` and `bin` dirs:

```nix
self: super:

{
  m = self.stdenv.mkDerivation {
    name = "m";
    unpackPhase = "true";
    # We have to create lib and bin to make it "look like"
    # a library
    installPhase = ''
    mkdir -p $out/lib
    mkdir -p $out/bin
    '';
  };
}
```

**Comment by ramirez7** [comment]
FYI @o1lo01ol1o @peterbecich https://github.com/input-output-hk/haskell.nix/pull/1453 fixes this issue upstream. I confirmed on `haskell.nix` `HEAD` with `ghc923` that `hgeometry` now works :+1:
