### ISSUE TITLE
Question on dependent types / Illegal type: `2'

### ISSUE THREAD

**Issue by krcurtis** [noinia/hgeometry#144]
Hi,

I'm trying to write a rotation function with a signature like:
```
rotate2d :: Double -> Transformation 2 Double
```

but I keep running into errors like 

```
Illegal type: `2' Perhaps you intended to use DataKinds

Illegal kind signature: `2'
      Perhaps you intended to use KindSignatures
```

and so on.  I see that hgeometry supports Data.Geometry.Vector.Vector 2 r but what is the right way to write something similar for my transformation that works with hgeometry?

Thanks

**Comment by Lemmih** [comment]
Try adding `{-# LANGUAGE DataKinds #-}` to the top of your file.

**Comment by krcurtis** [comment]
That fixed it, thanks
