### ISSUE TITLE
Algorithms.Geometry.LineSegmentIntersection.BentleyOttmann open intervals

### ISSUE THREAD

**Issue by aavogt** [noinia/hgeometry#161]
Hi Thanks for writing hgeometry!

```haskell
-- | Algorithms.Geometry.LineSegmentIntersection.BentleyOttmann.intersections
-- applied to opencv contours returns excess points like these:
--
-- >  , ( Point2 103.0 41.0
-- >    , Associated
-- >        { _endPointOf =
-- >            fromList
-- >              [ ( ( Point2 101.0 45.0 , Point2 103.0 41.0 )
-- >                , OpenLineSegment
-- >                    (Point2 101.0 45.0 :+ 0) (Point2 103.0 41.0 :+ 0) :|
-- >                    []
-- >                )
-- >              , ( ( Point2 103.0 41.0 , Point2 95.0 41.0 )
-- >                , OpenLineSegment
-- >                    (Point2 103.0 41.0 :+ 0) (Point2 95.0 41.0 :+ 0) :|
-- >                    []
-- >                )
-- >              ]
-- >        , _interiorTo = fromList []
-- >        }
-- >    )
removeOpens :: Eq r => Intersections p r -> Intersections p r
removeOpens = M.mapMaybeWithKey $ \ p (Associated ep interior) ->  
   let ensureEnough m = do
           guard (M.size m + M.size interior > 1)
           Just m
       f1 p1p2 = NE.nonEmpty . NE.filter (f2 p1p2)
       f2 (p1, p2) (LineSegment pi1 pi2) = 
               (isClosed pi1 || p1 /= p) && (isClosed pi2 || p2 /= p)
   in Associated <$> ensureEnough (M.mapMaybeWithKey f1 ep) <*> Just interior
```
You could include this function, but maybe it's better to avoid generating these points in the first place.

And is it intended for each user to define `makeLenses ''Associated`?

**Comment by noinia** [comment]
Oh thanks for reporting! It seems I incorrectly assumed that all segments were closed when implementing that algorithm. I think it indeed should not be too complicated to incorporate open endpoints as well. 

One complication may be if we essentially have two copies of the segment: one open and one closed, then they do intersect; we should make sure to report that appropriately somehow. Anyway, I'll see if I can produce a fix for this. :) 

> And is it intended for each user to define makeLenses ''Associated?

Hmm that does not seem very convenient, I guess I should already include that as well ;)

**Comment by noinia** [comment]
I think #175 should fix this. As I mentioned in the previous message; it was a bit annoying to deal with the various cases (open segments vs closed segments vs some mix) properly. I think/hope the current implementation takes care of all of the cases appropriately :).
