### ISSUE TITLE
sqDistanceToSegArg errors when result should be an open endpoint

### ISSUE THREAD

**Issue by damon-sava-stanley** [noinia/hgeometry#170]
Howdy. As per the title, there's an issue with `LineSegment`'s `sqDistanceToSegArg` shown by the following code.

```haskell
let ls = OpenLineSegment (Point2 0 0 :+ ()) (Point2 1 0 :+ ())
    p = Point2 2 0
in  snd (sqDistanceToSegArg p ls) == Point2 1 0
```

This should return `True` as per the documentation

> Note that if the segment is *open*, the closest point
> returned may be one of the (open) end points, even though technically the
> end point does not lie on the segment. (The true closest point then lies
> arbitrarily close to the end point). 

Instead it throws `Prelude.foldl1: empty list`. This is because although the implementation (correctly) adds the endpoints as candidates it, incorrectly, filters them out as not on the list.

**Comment by noinia** [comment]
Thanks for reporting this! Fixed in the above PR (which also introduces a typeclass for things for which we can compute a distance to)
