### ISSUE TITLE
Orphan Instances Arbitrary

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [noinia/hgeometry#22]
Would there be an advantage to declaring the Arbitrary instances from Test.QuickCheck.HGeometryInstances in the files that the types are declared in?

**Comment by noinia** [comment]
I think they are in a separate module for historic reason (initially that module was only part of the testsuite, but then it got moved into the main library). But maybe moving them into the proper modules would indeed be better.

**Comment by noinia** [comment]
fixed.
