### ISSUE TITLE
Remove IPE from Tests

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [noinia/hgeometry#24]
I have noticed that a lot of tests are dependent on .ipe data files. There seems to be nothing special about the data that couldn't be in the haskell test files. I propose having the data converted to the proper haskell geometry data type and placed in the correct test file.

This is a good idea because:
- it removes the dependence on the Ipe modules
- it the data file is changed the test will not be broken.

**Comment by noinia** [comment]
Hmm, I'm a bit sceptical. I find creating geometric objects by manually giving lists of coordinates very tedious. I'd much rather actually *draw* the geometric objects. That is what the current setup with the ipe files allows us to do. Furthermore, it easily allows us to view the geometry involved. Once again, this makes figuring out what is happening much easier than looking at lists of coordinates.

But in terms of dependencies it should not be that much of an issue I think right? hgeometry-core (the library) depends on nothing in particular, hgeometry-ipe depends on hgeometry-core, and the test-suite of hgeometry-core depends on hgeometry-ipe. That should be possible no?

**Comment by BebeSparkelSparkel** [comment]
You are right that it’s nice to be able to visualize the geometric objects. Also, I think it is good to compartmentalize things.
What do you think about having an isomorphism between the ipe format and a native haskell format?
This will allow you to create your test data with a compatible ipe gui editor and visualize the haskell data.

What I’m mostly concerned about is having a maze of data files with spaghetti links to tests, and it discourages using property tests.

**Comment by noinia** [comment]
To be honest, this is probably not going to happen at this point.
