### ISSUE TITLE
hgeometry-point haddocks missing

### ISSUE THREAD

**Issue by aavogt** [noinia/hgeometry#251]
I'm trying to figure out how to use the new hgeometry. When I generate haddocks `/home/aavogt/.cabal/store/ghc-9.6.6/hgeometry-1.0.0.0-60d0e11a422806c4e7a540303b7fd84c9bbc5b34c16ded481347b8e58081048b/share/doc/html/src/HGeometry.PolyLine.Simplification.DouglasPeucker.html` doesn't have a link to the Point_ or HasSquaredEuclideanDistance constraints/classes:

![image](https://github.com/user-attachments/assets/e761a817-2675-40cb-ba18-2e1147313245)

`/home/aavogt/.cabal/store/ghc-9.6.6/hgeometry-1.0.0.0-l-point-2504875e1b4fcd7c8d1e883b0082b2a22faa874a6ced693e231819f9ba006f0e` probably contains the classes, but there is no html for that library. I use `cabal 3.10.3.0`. Other cross-package hyperlinks work, though this is the first time I've seen one cabal file with multiple libraries.

**Comment by aavogt** [comment]
When I rebuild it with cabal-install version 3.12.1.0 the hyperlinks work.

**Comment by noinia** [comment]
Oh, well spotted. It seems the haddocks generated using CI also have this issue. I'll bump the cabal version used there as well then :).
