### ISSUE TITLE
Data.Geometry.CircularSeq.isShiftOf algorithm

### ISSUE THREAD

**Issue by mpilgrem** [noinia/hgeometry#26]
Is the `Data.Geometry.CircularSeq.isShiftOf` algorithm correct? For example:
~~~~
c1 :: CSeq Int
c1 = fromList [1, 2, 1, 3]

c2 :: CSeq Int
c2 = rotateNL 2 c1

isShiftOf c1 c2
False
~~~~

In:
~~~~
-- | Test if the circular list is a cyclic shift of the second list.
-- Running time: O(n), where n is the size of the smallest list
isShiftOf         :: Eq a => CSeq a -> CSeq a -> Bool
xs `isShiftOf` ys = let rest = tail . F.toList . leftElements
                    in maybe False (\xs' -> rest xs' == rest ys) $
                       rotateTo (focus ys) xs
~~~~
This seems to me to assume that if the focus of `ys` is in `xs`, then it is unique in `xs`.

**Comment by mpilgrem** [comment]
That is, perhaps all of the rotations of the `xs` that pass the filter in the underlying `findRotateTo` should be tested, not just the first? Something like:
~~~~
isShiftOf         :: Eq a => CSeq a -> CSeq a -> Bool
xs `isShiftOf` ys = let fy = focus ys
                        rs = filter (\xs' -> focus xs' == fy) (allRotations' xs)
                    in  length xs == length ys && elem ys rs
~~~~
and with `length xs == length ys` being a first hurdle to be cleared?

**Comment by noinia** [comment]
Ah, that certainly looks like a bug. I'll see if I can fix that. I may have to look where isShiftOf is actually used and if/how we can keep the O(n) running time.

**Comment by noinia** [comment]
I just implemented the Knuth-Morris-Pratt string searching algorithm and use that to test for circular shifts. That should fix this issue :).

Thanks again for reporting!

**Comment by mpilgrem** [comment]
@noinia, perhaps I have misunderstood what is meant by a circular shift, but - in the new algorithm - is it sufficient that the elements of one circular sequence are a 'substring' of the other? You now have, for example:
~~~~
c1 :: CSeq Int
c1 = fromList [1, 2, 3, 4]

c2 :: CSeq Int
c2 = fromList [3, 2]

c1 `isShiftOf` c2
True
~~~~

That is because `[3, 2]` is a 'substring' of `[1, 4, 3, 2, 1, 4, 3, 2]`

**Comment by mpilgrem** [comment]
Also, I see in `Algorithms.StringSearch.KMP.isSubStringOf` you convert from a foldable to `Data.Vector.Vector a` using `V.fromList . F.toList`.

I wanted to do something similar recently and found `VectorBuilder.Vector.build . VectorBuilder.Builder.foldable` from package `vector-builder >= 0.3.7` to be faster than going via a list.

**Comment by noinia** [comment]
Ah, well spotted; I am/was just being an idiot. I made another attempt at fixing it (basically by adding the constraint that the lengths should be the same). If my reasoning is right this time that should actually give the correct result. I also added a bit more documentation, and used VectorBuilder as you suggested. :)
