### ISSUE TITLE
Github Pages for hosting dev docs and badges.

### ISSUE THREAD

**Issue by Lemmih** [noinia/hgeometry#44]
I'd like to configure and host an API coverage badge (![badge](https://camo.githubusercontent.com/e720b7c2def7160247e60beb18de9b9c0df7018d81549d84580594ff4de1133d/68747470733a2f2f696d672e736869656c64732e696f2f656e64706f696e743f75726c3d68747470732533412532462532467265616e696d6174652e6769746875622e696f2532467265616e696d617465253246686164646f636b5f62616467652e6a736f6e)) for the various hgeometry libraries. The github pages could also host up-to-date haddock docs.

**Comment by noinia** [comment]
That is a good idea. What should we do in order to set that up?

**Comment by Lemmih** [comment]
You need to go to 'Settings', scroll down to the 'GitHub Pages' section, and enable GitHub Pages. Set it to use a new branch. That way, the files we host (haddock docs, coverage reports, etc) won't show up in the master branch.

**Comment by Lemmih** [comment]
Alternatively you could bump my role from 'Write' to 'Maintain' and I would configure it.

**Comment by noinia** [comment]
I now enabled the github pages thing for the 'docs' folder in the docs branch. That seems to sort of work now, as it now hosts a copy of the readme at https://noinia.github.io/hgeometry/

**Comment by Lemmih** [comment]
The haddock documentation and coverage badge are now up and running. Clicking on the coverage badge takes you to the haddock documentation. As we write more documentation, the badge will update automatically.

**Comment by noinia** [comment]
Awesome! :)
