### ISSUE TITLE
Wrong result from inPolygon when used with Double values

### ISSUE THREAD

**Issue by marhop** [noinia/hgeometry#47]
Hi,

using the [inPolygon](https://hackage.haskell.org/package/hgeometry-0.11.0.0/docs/Data-Geometry-Polygon.html#v:inPolygon) function with Double values sometimes returns wrong results while working correctly with (presumably) Integral values:

```
>>> (Point2 340000 5700000) `inPolygon` fromPoints [Point2 334882 5689376 :+ (), Point2 334882 5714648 :+ (), Point2 348981 5714648 :+ (), Point2 348981 5689376 :+ ()]
Inside -- OK
>>> (Point2 340000 5700000) `inPolygon` fromPoints [Point2 334882.785 5689376.404 :+ (), Point2 334882.785 5714648.124 :+ (), Point2 348981.954 5714648.124 :+ (), Point2 348981.954 5689376.404 :+ ()]
Outside -- Should be Inside!
```
Am I doing something wrong or is this a bug?

Thanks,
Martin

**Comment by Lemmih** [comment]
Doubles are approximations rather than exact values. If you want exact results then you have to use Rational.

With Double:
```
λ> (Point2 340000 5700000 :: Point 2 Double) `inPolygon` fromPoints [Point2 334882.785 5689376.404 :+ (), Point2 334882.785 5714648.124 :+ (), Point2 348981.954 5714648.124 :+ (), Point2 348981.954 5689376.404 :+ ()]
Outside
```

With Rational:
```
λ> (Point2 340000 5700000 :: Point 2 Rational) `inPolygon` fromPoints [Point2 334882.785 5689376.404 :+ (), Point2 334882.785 5714648.124 :+ (), Point2 348981.954 5714648.124 :+ (), Point2 348981.954 5689376.404 :+ ()]
Inside
```

This is simply the nature of doubles. When in doubt, use Rationals.
```
λ> [1,1.1 .. 1.2]
[1.0,1.1,1.2000000000000002]
```

**Comment by marhop** [comment]
Ah OK, I feared I was running into floating point precision errors here ... And wasn't really aware of the Rational type, so at least I learned something. ;-) Thank you!
