### ISSUE TITLE
sqDistancetoArg

### ISSUE THREAD

**Issue by tonymorris** [noinia/hgeometry#5]
When I use `sqDistanceToArg` one of the points returned is not on the boundary of the polygon.

    > let poly :: SimplePolygon () Rational; poly = (fromPoints . map ext) [point2 61 1500, point2 89 2200, point2 82.5 2200, point2 68 1950, point2 52.5 1500] in sqDistanceToArg (point2 70 2100) . supportingLine <$> outerBoundaryEdges poly
    CSeq [(140625 % 626,Point2 [53195 % 626,1314225 % 626]),(10000 % 1,Point2 [70 % 1,2200 % 1]),(11222500 % 250841,Point2 [19233870 % 250841,526668950 % 250841]),(8122500 % 810961,Point2 [59332270 % 810961,1702929750 % 810961]),(360000 % 1,Point2 [70 % 1,1500 % 1])]

The point `Point2 [70 % 1,1500 % 1]` is not within the polygon, yet it is returned as the nearest point on a line.

Is this a bug?

**Comment by noinia** [comment]
I think there is some confusion in terminology: A (non-vertical) line l is the set of points given by the equation y=ax + b, for some real numbers a and b. A linesegment is the part of some line l between two points. Hence, a linesegment has something like a length; a line does not (i.e. its length would be infiinite). 

Your code snippet asks for all edges (line segments) bounding the polygon, for each segment asks for the line containing such a segment (= the supporting line), and then asks for the closest point (using the squared Euclidean distance) *on the line* to some point. 

See also the drawing below. the orange line (which extends on the left and right to infinity) is the supporting line for the bottom edge of the red polygon, and the black point p is indeed the point on the orange line closest to q (the blue point). Hopefully that clears up the confusion. 

![sketch](https://cloud.githubusercontent.com/assets/991345/21156754/4feb32c6-c177-11e6-9ee6-4aef9bdb9897.png)

**Comment by tonymorris** [comment]
OK understood, thanks.

**Comment by noinia** [comment]
Oh by the way; I think you want the point *on* a segment, closest to q. I don't think hgeometry currently has such a function, but I would be open to add it.
