### ISSUE TITLE
0.5.1.0

### ISSUE THREAD

**Issue by tonymorris** [noinia/hgeometry#6]
Can we publish 0.5.1.0 to hackage?

**Comment by noinia** [comment]
That seems like a reasonable idea. I would still like to add some testing stuff for some of the planar-graph code I added recently. Once I've finished with that I'll publish a new version on Hackage. I'll try and do that some time this week :).

**Comment by noinia** [comment]
I just pushed a new version, labelled 0.6.0.0, to Hackage.
