### ISSUE TITLE
Consider adding hgeometry to stackage?

### ISSUE THREAD

**Issue by niteria** [noinia/hgeometry#7]
Adding to `stackage` would make sure that your package builds with recent versions of dependencies + it can be used in a bigger project.

https://github.com/fpco/stackage#add-your-package has the steps on how to do it.

**Comment by Lemmih** [comment]
Why particular reasons for keeping this package off of stackage?

**Comment by Lemmih** [comment]
I can help with maintenance and setting up a workflow for automatically building against stackage nightly. @noinia

**Comment by noinia** [comment]
Sorry for the late reply. In principle I'm not opposed to adding hgeometry to stackage. However, that means that some level of regular/additional maintenance is required. I've always been a bit hesitant to commit to that. Anything that would help in making that easier wouls be greatly appreciated.

**Comment by Lemmih** [comment]
hgeometry and hgeometry-combinatorial are in Stackage nightly. They will be in the next LTS.

**Comment by Lemmih** [comment]
LTS-17.0 contains hgeometry. Great success. Closing this issue.

**Comment by mrehayden1** [comment]
Was it decided to remove hgeometry from stackage? I can't see it in newer LTS.

It seems to have been removed around the release of GHC 9.4
