### ISSUE TITLE
Update to 8.4.1 and release?

### ISSUE THREAD

**Issue by gbaz** [noinia/hgeometry#8]
The semigroup-monoid changes mean that this no longer compiles with new base. It would be nice to do a new release that was 8.4.1 compatible.

**Comment by noinia** [comment]
I finally had some time to finish the stuff I wanted to include in a new version and released it. The new release, 0.7.0.0, is compatible with at least GHC 8.2 and 8.4. Anyway, thanks for the report, and sorry for the long wait.
